version: '3.5'
services:
    db:
      container_name: db_csvJsonTest
      image: mongo
      command: mongod --quiet --logpath /dev/null
      ports: 
          - 27017:27017

    api:
        depends_on:
            - db
        volumes: 
            - ./server:/app
            - ./server/node_modules:/app/node_modules
        container_name: backend_csvJsonTest
        environment:
            - DATABASE_URL=mongodb://db/csvJsonTest
        build:
            context: ./server
        ports:
            - "5000:5000"
        command: yarn start
    
    
    